name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    if: false
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - run: sudo apt update
    - run: sudo apt install nasm libdbus-1-dev libfreetype-dev libfontconfig-dev
    - run: pip install hatch
    - run: hatch build
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - run: pip install hatch
    - run: hatch build
  build-windows:
    if: false
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        echo C:\msys64\usr\bin >> $env:GITHUB_PATH
        echo C:\msys64\ucrt64\bin >> $env:GITHUB_PATH
    - run: |
        pacman --noconfirm -Syu
        pacman --noconfirm -S make
    #- run: winget install --accept-package-agreements --accept-source-agreements --disable-interactivity NASM.NASM
    - run: |
        make --version
        Get-Command make
        Get-Command perl
        Get-Command cmake
        Get-Command nasm
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - run: pip install hatch ninja
    - run: hatch build
